<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace LT\eBaySDK\Inventory\Services;

class InventoryService extends \LT\eBaySDK\Inventory\Services\InventoryBaseService
{
    const API_VERSION = 'v1';

    /**
     * @property array $operations Associative array of operations provided by the service.
     */
    protected static $operations = [
        'BulkUpdatePriceAndQuantity' => [
            'method' => 'POST',
            'resource' => 'bulk_update_price_quantity',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\BulkUpdatePriceAndQuantityRestResponse',
            'params' => [
            ]
        ],
        'CreateOrReplaceInventoryItem' => [
            'method' => 'PUT',
            'resource' => 'inventory_item/{sku}',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\CreateOrReplaceInventoryItemRestResponse',
            'params' => [
                'sku' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'DeleteInventoryItem' => [
            'method' => 'DELETE',
            'resource' => 'inventory_item/{sku}',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\DeleteInventoryItemRestResponse',
            'params' => [
                'sku' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetInventoryItem' => [
            'method' => 'GET',
            'resource' => 'inventory_item/{sku}',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\GetInventoryItemRestResponse',
            'params' => [
                'sku' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetInventoryItems' => [
            'method' => 'GET',
            'resource' => 'inventory_item',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\GetInventoryItemsRestResponse',
            'params' => [
                'limit' => [
                    'valid' => ['string']
                ],
                'offset' => [
                    'valid' => ['string']
                ]
            ]
        ],
        'CreateOrReplaceInventoryItemGroup' => [
            'method' => 'PUT',
            'resource' => 'inventory_item_group/{inventoryItemGroupKey}',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\CreateOrReplaceInventoryItemGroupRestResponse',
            'params' => [
                'inventoryItemGroupKey' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'DeleteInventoryItemGroup' => [
            'method' => 'DELETE',
            'resource' => 'inventory_item_group/{inventoryItemGroupKey}',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\DeleteInventoryItemGroupRestResponse',
            'params' => [
                'inventoryItemGroupKey' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetInventoryItemGroup' => [
            'method' => 'GET',
            'resource' => 'inventory_item_group/{inventoryItemGroupKey}',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\GetInventoryItemGroupRestResponse',
            'params' => [
                'inventoryItemGroupKey' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'BulkMigrateListings' => [
            'method' => 'POST',
            'resource' => 'bulk_migrate_listing',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\BulkMigrateListingsRestResponse',
            'params' => [
            ]
        ],
        'CreateInventoryLocation' => [
            'method' => 'POST',
            'resource' => 'location/{merchantLocationKey}',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\CreateInventoryLocationRestResponse',
            'params' => [
                'merchantLocationKey' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'DeleteInventoryLocation' => [
            'method' => 'DELETE',
            'resource' => 'location/{merchantLocationKey}',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\DeleteInventoryLocationRestResponse',
            'params' => [
                'merchantLocationKey' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'DisableInventoryLocation' => [
            'method' => 'POST',
            'resource' => 'location/{merchantLocationKey}/disable',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\DisableInventoryLocationRestResponse',
            'params' => [
                'merchantLocationKey' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'EnableInventoryLocation' => [
            'method' => 'POST',
            'resource' => 'location/{merchantLocationKey}/enable',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\EnableInventoryLocationRestResponse',
            'params' => [
                'merchantLocationKey' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetInventoryLocation' => [
            'method' => 'GET',
            'resource' => 'location/{merchantLocationKey}',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\GetInventoryLocationRestResponse',
            'params' => [
                'merchantLocationKey' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetInventoryLocations' => [
            'method' => 'GET',
            'resource' => 'location',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\GetInventoryLocationsRestResponse',
            'params' => [
                'limit' => [
                    'valid' => ['string']
                ],
                'offset' => [
                    'valid' => ['string']
                ]
            ]
        ],
        'UpdateInventoryLocation' => [
            'method' => 'POST',
            'resource' => 'location/{merchantLocationKey}/update_location_details',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\UpdateInventoryLocationRestResponse',
            'params' => [
                'merchantLocationKey' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'CreateOffer' => [
            'method' => 'POST',
            'resource' => 'offer',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\CreateOfferRestResponse',
            'params' => [
            ]
        ],
        'DeleteOffer' => [
            'method' => 'DELETE',
            'resource' => 'offer/{offerId}',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\DeleteOfferRestResponse',
            'params' => [
                'offerId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetListingFees' => [
            'method' => 'POST',
            'resource' => 'offer/get_listing_fees',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\GetListingFeesRestResponse',
            'params' => [
            ]
        ],
        'GetOffer' => [
            'method' => 'GET',
            'resource' => 'offer/{offerId}',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\GetOfferRestResponse',
            'params' => [
                'offerId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetOffers' => [
            'method' => 'GET',
            'resource' => 'offer',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\GetOffersRestResponse',
            'params' => [
                'format' => [
                    'valid' => ['string']
                ],
                'limit' => [
                    'valid' => ['string']
                ],
                'marketplace_id' => [
                    'valid' => ['string']
                ],
                'offset' => [
                    'valid' => ['string']
                ],
                'sku' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'PublishOffer' => [
            'method' => 'POST',
            'resource' => 'offer/{offerId}/publish',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\PublishOfferRestResponse',
            'params' => [
                'offerId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'WithdrawOffer' => [
            'method' => 'POST',
            'resource' => 'offer/{offerId}/withdraw',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\WithdrawOfferRestResponse',
            'params' => [
                'offerId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'UpdateOffer' => [
            'method' => 'PUT',
            'resource' => 'offer/{offerId}',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\UpdateOfferRestResponse',
            'params' => [
                'offerId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'CreateOrReplaceProductCompatibility' => [
            'method' => 'PUT',
            'resource' => 'inventory_item/{sku}/product_compatibility',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\CreateOrReplaceProductCompatibilityRestResponse',
            'params' => [
                'sku' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'DeleteProductCompatibility' => [
            'method' => 'DELETE',
            'resource' => 'inventory_item/{sku}/product_compatibility',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\DeleteProductCompatibilityRestResponse',
            'params' => [
                'sku' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetProductCompatibility' => [
            'method' => 'GET',
            'resource' => 'inventory_item/{sku}/product_compatibility',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\GetProductCompatibilityRestResponse',
            'params' => [
                'sku' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'PublishOfferByInventoryItemGroup' => [
            'method' => 'POST',
            'resource' => 'offer/publish_by_inventory_item_group',
            'responseClass' => '\LT\eBaySDK\Inventory\Types\PublishOfferByInventoryItemGroupRestResponse',
            'params' => [
            ]
        ]
    ];

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\BulkUpdatePriceAndQuantityRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\BulkUpdatePriceAndQuantityRestResponse
     */
    public function bulkUpdatePriceAndQuantity(\LT\eBaySDK\Inventory\Types\BulkUpdatePriceAndQuantityRestRequest $request)
    {
        return $this->bulkUpdatePriceAndQuantityAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\BulkUpdatePriceAndQuantityRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bulkUpdatePriceAndQuantityAsync(\LT\eBaySDK\Inventory\Types\BulkUpdatePriceAndQuantityRestRequest $request)
    {
        return $this->callOperationAsync('BulkUpdatePriceAndQuantity', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\CreateOrReplaceInventoryItemRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\CreateOrReplaceInventoryItemRestResponse
     */
    public function createOrReplaceInventoryItem(\LT\eBaySDK\Inventory\Types\CreateOrReplaceInventoryItemRestRequest $request)
    {
        return $this->createOrReplaceInventoryItemAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\CreateOrReplaceInventoryItemRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createOrReplaceInventoryItemAsync(\LT\eBaySDK\Inventory\Types\CreateOrReplaceInventoryItemRestRequest $request)
    {
        return $this->callOperationAsync('CreateOrReplaceInventoryItem', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\DeleteInventoryItemRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\DeleteInventoryItemRestResponse
     */
    public function deleteInventoryItem(\LT\eBaySDK\Inventory\Types\DeleteInventoryItemRestRequest $request)
    {
        return $this->deleteInventoryItemAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\DeleteInventoryItemRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteInventoryItemAsync(\LT\eBaySDK\Inventory\Types\DeleteInventoryItemRestRequest $request)
    {
        return $this->callOperationAsync('DeleteInventoryItem', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetInventoryItemRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\GetInventoryItemRestResponse
     */
    public function getInventoryItem(\LT\eBaySDK\Inventory\Types\GetInventoryItemRestRequest $request)
    {
        return $this->getInventoryItemAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetInventoryItemRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInventoryItemAsync(\LT\eBaySDK\Inventory\Types\GetInventoryItemRestRequest $request)
    {
        return $this->callOperationAsync('GetInventoryItem', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetInventoryItemsRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\GetInventoryItemsRestResponse
     */
    public function getInventoryItems(\LT\eBaySDK\Inventory\Types\GetInventoryItemsRestRequest $request)
    {
        return $this->getInventoryItemsAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetInventoryItemsRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInventoryItemsAsync(\LT\eBaySDK\Inventory\Types\GetInventoryItemsRestRequest $request)
    {
        return $this->callOperationAsync('GetInventoryItems', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\CreateOrReplaceInventoryItemGroupRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\CreateOrReplaceInventoryItemGroupRestResponse
     */
    public function createOrReplaceInventoryItemGroup(\LT\eBaySDK\Inventory\Types\CreateOrReplaceInventoryItemGroupRestRequest $request)
    {
        return $this->createOrReplaceInventoryItemGroupAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\CreateOrReplaceInventoryItemGroupRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createOrReplaceInventoryItemGroupAsync(\LT\eBaySDK\Inventory\Types\CreateOrReplaceInventoryItemGroupRestRequest $request)
    {
        return $this->callOperationAsync('CreateOrReplaceInventoryItemGroup', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\DeleteInventoryItemGroupRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\DeleteInventoryItemGroupRestResponse
     */
    public function deleteInventoryItemGroup(\LT\eBaySDK\Inventory\Types\DeleteInventoryItemGroupRestRequest $request)
    {
        return $this->deleteInventoryItemGroupAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\DeleteInventoryItemGroupRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteInventoryItemGroupAsync(\LT\eBaySDK\Inventory\Types\DeleteInventoryItemGroupRestRequest $request)
    {
        return $this->callOperationAsync('DeleteInventoryItemGroup', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetInventoryItemGroupRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\GetInventoryItemGroupRestResponse
     */
    public function getInventoryItemGroup(\LT\eBaySDK\Inventory\Types\GetInventoryItemGroupRestRequest $request)
    {
        return $this->getInventoryItemGroupAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetInventoryItemGroupRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInventoryItemGroupAsync(\LT\eBaySDK\Inventory\Types\GetInventoryItemGroupRestRequest $request)
    {
        return $this->callOperationAsync('GetInventoryItemGroup', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\BulkMigrateListingsRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\BulkMigrateListingsRestResponse
     */
    public function bulkMigrateListings(\LT\eBaySDK\Inventory\Types\BulkMigrateListingsRestRequest $request)
    {
        return $this->bulkMigrateListingsAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\BulkMigrateListingsRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bulkMigrateListingsAsync(\LT\eBaySDK\Inventory\Types\BulkMigrateListingsRestRequest $request)
    {
        return $this->callOperationAsync('BulkMigrateListings', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\CreateInventoryLocationRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\CreateInventoryLocationRestResponse
     */
    public function createInventoryLocation(\LT\eBaySDK\Inventory\Types\CreateInventoryLocationRestRequest $request)
    {
        return $this->createInventoryLocationAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\CreateInventoryLocationRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createInventoryLocationAsync(\LT\eBaySDK\Inventory\Types\CreateInventoryLocationRestRequest $request)
    {
        return $this->callOperationAsync('CreateInventoryLocation', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\DeleteInventoryLocationRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\DeleteInventoryLocationRestResponse
     */
    public function deleteInventoryLocation(\LT\eBaySDK\Inventory\Types\DeleteInventoryLocationRestRequest $request)
    {
        return $this->deleteInventoryLocationAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\DeleteInventoryLocationRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteInventoryLocationAsync(\LT\eBaySDK\Inventory\Types\DeleteInventoryLocationRestRequest $request)
    {
        return $this->callOperationAsync('DeleteInventoryLocation', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\DisableInventoryLocationRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\DisableInventoryLocationRestResponse
     */
    public function disableInventoryLocation(\LT\eBaySDK\Inventory\Types\DisableInventoryLocationRestRequest $request)
    {
        return $this->disableInventoryLocationAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\DisableInventoryLocationRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function disableInventoryLocationAsync(\LT\eBaySDK\Inventory\Types\DisableInventoryLocationRestRequest $request)
    {
        return $this->callOperationAsync('DisableInventoryLocation', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\EnableInventoryLocationRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\EnableInventoryLocationRestResponse
     */
    public function enableInventoryLocation(\LT\eBaySDK\Inventory\Types\EnableInventoryLocationRestRequest $request)
    {
        return $this->enableInventoryLocationAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\EnableInventoryLocationRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function enableInventoryLocationAsync(\LT\eBaySDK\Inventory\Types\EnableInventoryLocationRestRequest $request)
    {
        return $this->callOperationAsync('EnableInventoryLocation', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetInventoryLocationRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\GetInventoryLocationRestResponse
     */
    public function getInventoryLocation(\LT\eBaySDK\Inventory\Types\GetInventoryLocationRestRequest $request)
    {
        return $this->getInventoryLocationAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetInventoryLocationRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInventoryLocationAsync(\LT\eBaySDK\Inventory\Types\GetInventoryLocationRestRequest $request)
    {
        return $this->callOperationAsync('GetInventoryLocation', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetInventoryLocationsRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\GetInventoryLocationsRestResponse
     */
    public function getInventoryLocations(\LT\eBaySDK\Inventory\Types\GetInventoryLocationsRestRequest $request)
    {
        return $this->getInventoryLocationsAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetInventoryLocationsRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInventoryLocationsAsync(\LT\eBaySDK\Inventory\Types\GetInventoryLocationsRestRequest $request)
    {
        return $this->callOperationAsync('GetInventoryLocations', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\UpdateInventoryLocationRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\UpdateInventoryLocationRestResponse
     */
    public function updateInventoryLocation(\LT\eBaySDK\Inventory\Types\UpdateInventoryLocationRestRequest $request)
    {
        return $this->updateInventoryLocationAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\UpdateInventoryLocationRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateInventoryLocationAsync(\LT\eBaySDK\Inventory\Types\UpdateInventoryLocationRestRequest $request)
    {
        return $this->callOperationAsync('UpdateInventoryLocation', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\CreateOfferRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\CreateOfferRestResponse
     */
    public function createOffer(\LT\eBaySDK\Inventory\Types\CreateOfferRestRequest $request)
    {
        return $this->createOfferAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\CreateOfferRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createOfferAsync(\LT\eBaySDK\Inventory\Types\CreateOfferRestRequest $request)
    {
        return $this->callOperationAsync('CreateOffer', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\DeleteOfferRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\DeleteOfferRestResponse
     */
    public function deleteOffer(\LT\eBaySDK\Inventory\Types\DeleteOfferRestRequest $request)
    {
        return $this->deleteOfferAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\DeleteOfferRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteOfferAsync(\LT\eBaySDK\Inventory\Types\DeleteOfferRestRequest $request)
    {
        return $this->callOperationAsync('DeleteOffer', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetListingFeesRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\GetListingFeesRestResponse
     */
    public function getListingFees(\LT\eBaySDK\Inventory\Types\GetListingFeesRestRequest $request)
    {
        return $this->getListingFeesAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetListingFeesRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getListingFeesAsync(\LT\eBaySDK\Inventory\Types\GetListingFeesRestRequest $request)
    {
        return $this->callOperationAsync('GetListingFees', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetOfferRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\GetOfferRestResponse
     */
    public function getOffer(\LT\eBaySDK\Inventory\Types\GetOfferRestRequest $request)
    {
        return $this->getOfferAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetOfferRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOfferAsync(\LT\eBaySDK\Inventory\Types\GetOfferRestRequest $request)
    {
        return $this->callOperationAsync('GetOffer', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetOffersRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\GetOffersRestResponse
     */
    public function getOffers(\LT\eBaySDK\Inventory\Types\GetOffersRestRequest $request)
    {
        return $this->getOffersAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetOffersRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOffersAsync(\LT\eBaySDK\Inventory\Types\GetOffersRestRequest $request)
    {
        return $this->callOperationAsync('GetOffers', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\PublishOfferRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\PublishOfferRestResponse
     */
    public function publishOffer(\LT\eBaySDK\Inventory\Types\PublishOfferRestRequest $request)
    {
        return $this->publishOfferAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\PublishOfferRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function publishOfferAsync(\LT\eBaySDK\Inventory\Types\PublishOfferRestRequest $request)
    {
        return $this->callOperationAsync('PublishOffer', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\WithdrawOfferRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\WithdrawOfferRestResponse
     */
    public function withdrawOffer(\LT\eBaySDK\Inventory\Types\WithdrawOfferRestRequest $request)
    {
        return $this->withdrawOfferAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\WithdrawOfferRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function withdrawOfferAsync(\LT\eBaySDK\Inventory\Types\WithdrawOfferRestRequest $request)
    {
        return $this->callOperationAsync('WithdrawOffer', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\UpdateOfferRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\UpdateOfferRestResponse
     */
    public function updateOffer(\LT\eBaySDK\Inventory\Types\UpdateOfferRestRequest $request)
    {
        return $this->updateOfferAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\UpdateOfferRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateOfferAsync(\LT\eBaySDK\Inventory\Types\UpdateOfferRestRequest $request)
    {
        return $this->callOperationAsync('UpdateOffer', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\CreateOrReplaceProductCompatibilityRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\CreateOrReplaceProductCompatibilityRestResponse
     */
    public function createOrReplaceProductCompatibility(\LT\eBaySDK\Inventory\Types\CreateOrReplaceProductCompatibilityRestRequest $request)
    {
        return $this->createOrReplaceProductCompatibilityAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\CreateOrReplaceProductCompatibilityRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createOrReplaceProductCompatibilityAsync(\LT\eBaySDK\Inventory\Types\CreateOrReplaceProductCompatibilityRestRequest $request)
    {
        return $this->callOperationAsync('CreateOrReplaceProductCompatibility', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\DeleteProductCompatibilityRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\DeleteProductCompatibilityRestResponse
     */
    public function deleteProductCompatibility(\LT\eBaySDK\Inventory\Types\DeleteProductCompatibilityRestRequest $request)
    {
        return $this->deleteProductCompatibilityAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\DeleteProductCompatibilityRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteProductCompatibilityAsync(\LT\eBaySDK\Inventory\Types\DeleteProductCompatibilityRestRequest $request)
    {
        return $this->callOperationAsync('DeleteProductCompatibility', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetProductCompatibilityRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\GetProductCompatibilityRestResponse
     */
    public function getProductCompatibility(\LT\eBaySDK\Inventory\Types\GetProductCompatibilityRestRequest $request)
    {
        return $this->getProductCompatibilityAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\GetProductCompatibilityRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductCompatibilityAsync(\LT\eBaySDK\Inventory\Types\GetProductCompatibilityRestRequest $request)
    {
        return $this->callOperationAsync('GetProductCompatibility', $request);
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\PublishOfferByInventoryItemGroupRestRequest $request
     * @return \LT\eBaySDK\Inventory\Types\PublishOfferByInventoryItemGroupRestResponse
     */
    public function publishOfferByInventoryItemGroup(\LT\eBaySDK\Inventory\Types\PublishOfferByInventoryItemGroupRestRequest $request)
    {
        return $this->publishOfferByInventoryItemGroupAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Inventory\Types\PublishOfferByInventoryItemGroupRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function publishOfferByInventoryItemGroupAsync(\LT\eBaySDK\Inventory\Types\PublishOfferByInventoryItemGroupRestRequest $request)
    {
        return $this->callOperationAsync('PublishOfferByInventoryItemGroup', $request);
    }
}
