<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace LT\eBaySDK\Test\ProductMetadata\Types;

use LT\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesBulkResponse;

class GetCompatibilitySearchValuesBulkResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetCompatibilitySearchValuesBulkResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\LT\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesBulkResponse', $this->obj);
    }

    public function testExtendsGetProductSearchValuesResponse()
    {
        $this->assertInstanceOf('\LT\eBaySDK\ProductMetadata\Types\GetProductSearchValuesResponse', $this->obj);
    }
}
