<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace LT\eBaySDK\Test\ProductMetadata\Types;

use LT\eBaySDK\ProductMetadata\Types\ProductMetadataRequest;

class ProductMetadataRequestTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new ProductMetadataRequest();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\LT\eBaySDK\ProductMetadata\Types\ProductMetadataRequest', $this->obj);
    }

    public function testExtendsBaseRequest()
    {
        $this->assertInstanceOf('\LT\eBaySDK\ProductMetadata\Types\BaseRequest', $this->obj);
    }
}
