<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace LT\eBaySDK\Test\Taxonomy\Enums;

use LT\eBaySDK\Taxonomy\Enums\ItemToAspectCardinalityEnum;

class ItemToAspectCardinalityEnumTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new ItemToAspectCardinalityEnum();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\LT\eBaySDK\Taxonomy\Enums\ItemToAspectCardinalityEnum', $this->obj);
    }
}
