<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace LT\eBaySDK\Test\Metadata\Enums;

use LT\eBaySDK\Metadata\Enums\CompatibleVehicleTypeEnum;

class CompatibleVehicleTypeEnumTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new CompatibleVehicleTypeEnum();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\LT\eBaySDK\Metadata\Enums\CompatibleVehicleTypeEnum', $this->obj);
    }
}
