<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace LT\eBaySDK\Test\Marketing\Types;

use LT\eBaySDK\Marketing\Types\UpdateBidRestRequest;

class UpdateBidRestRequestTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new UpdateBidRestRequest();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\LT\eBaySDK\Marketing\Types\UpdateBidRestRequest', $this->obj);
    }

    public function testExtendsUpdateBidPercentageRequest()
    {
        $this->assertInstanceOf('\LT\eBaySDK\Marketing\Types\UpdateBidPercentageRequest', $this->obj);
    }
}
