<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace LT\eBaySDK\Account\Services;

class AccountService extends \LT\eBaySDK\Account\Services\AccountBaseService
{
    const API_VERSION = 'v1';

    /**
     * @property array $operations Associative array of operations provided by the service.
     */
    protected static $operations = [
        'CreateAFulfillmentPolicy' => [
            'method' => 'POST',
            'resource' => 'fulfillment_policy',
            'responseClass' => '\LT\eBaySDK\Account\Types\CreateAFulfillmentPolicyRestResponse',
            'params' => [
            ]
        ],
        'DeleteAFulfillmentPolicy' => [
            'method' => 'DELETE',
            'resource' => 'fulfillment_policy/{fulfillmentPolicyId}',
            'responseClass' => '\LT\eBaySDK\Account\Types\DeleteAFulfillmentPolicyRestResponse',
            'params' => [
                'fulfillmentPolicyId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetFulfillmentPoliciesByMarketplace' => [
            'method' => 'GET',
            'resource' => 'fulfillment_policy',
            'responseClass' => '\LT\eBaySDK\Account\Types\GetFulfillmentPoliciesByMarketplaceRestResponse',
            'params' => [
                'marketplace_id' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetAFulfillmentPolicyByID' => [
            'method' => 'GET',
            'resource' => 'fulfillment_policy/{fulfillmentPolicyId}',
            'responseClass' => '\LT\eBaySDK\Account\Types\GetAFulfillmentPolicyByIDRestResponse',
            'params' => [
                'fulfillmentPolicyId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetAFulfillmentPolicyByName' => [
            'method' => 'GET',
            'resource' => 'fulfillment_policy/get_by_policy_name',
            'responseClass' => '\LT\eBaySDK\Account\Types\GetAFulfillmentPolicyByNameRestResponse',
            'params' => [
                'marketplace_id' => [
                    'valid' => ['string'],
                    'required' => true
                ],
                'name' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'UpdateAFulfillmentPolicy' => [
            'method' => 'PUT',
            'resource' => 'fulfillment_policy/{fulfillmentPolicyId}',
            'responseClass' => '\LT\eBaySDK\Account\Types\UpdateAFulfillmentPolicyRestResponse',
            'params' => [
                'fulfillmentPolicyId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'CreateAPaymentPolicy' => [
            'method' => 'POST',
            'resource' => 'payment_policy',
            'responseClass' => '\LT\eBaySDK\Account\Types\CreateAPaymentPolicyRestResponse',
            'params' => [
            ]
        ],
        'DeleteAPaymentPolicy' => [
            'method' => 'DELETE',
            'resource' => 'payment_policy/{payment_policy_id}',
            'responseClass' => '\LT\eBaySDK\Account\Types\DeleteAPaymentPolicyRestResponse',
            'params' => [
                'payment_policy_id' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetPaymentPoliciesByMarketplace' => [
            'method' => 'GET',
            'resource' => 'payment_policy',
            'responseClass' => '\LT\eBaySDK\Account\Types\GetPaymentPoliciesByMarketplaceRestResponse',
            'params' => [
                'marketplace_id' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetAPaymentPolicyByID' => [
            'method' => 'GET',
            'resource' => 'payment_policy/{paymentPolicyId}',
            'responseClass' => '\LT\eBaySDK\Account\Types\GetAPaymentPolicyByIDRestResponse',
            'params' => [
                'paymentPolicyId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetAPaymentPolicyByName' => [
            'method' => 'GET',
            'resource' => 'payment_policy/get_by_policy_name',
            'responseClass' => '\LT\eBaySDK\Account\Types\GetAPaymentPolicyByNameRestResponse',
            'params' => [
                'marketplace_id' => [
                    'valid' => ['string'],
                    'required' => true
                ],
                'name' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'UpdateAPaymentPolicy' => [
            'method' => 'PUT',
            'resource' => 'payment_policy/{payment_policy_id}',
            'responseClass' => '\LT\eBaySDK\Account\Types\UpdateAPaymentPolicyRestResponse',
            'params' => [
                'payment_policy_id' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetAccountPrivileges' => [
            'method' => 'GET',
            'resource' => 'privilege',
            'responseClass' => '\LT\eBaySDK\Account\Types\GetAccountPrivilegesRestResponse',
            'params' => [
            ]
        ],
        'GetOptedInPrograms' => [
            'method' => 'GET',
            'resource' => 'program/get_opted_in_programs',
            'responseClass' => '\LT\eBaySDK\Account\Types\GetOptedInProgramsRestResponse',
            'params' => [
            ]
        ],
        'OptInToProgram' => [
            'method' => 'POST',
            'resource' => 'program/opt_in',
            'responseClass' => '\LT\eBaySDK\Account\Types\OptInToProgramRestResponse',
            'params' => [
            ]
        ],
        'OptOutOfProgram' => [
            'method' => 'POST',
            'resource' => 'program/opt_out',
            'responseClass' => '\LT\eBaySDK\Account\Types\OptOutOfProgramRestResponse',
            'params' => [
            ]
        ],
        'GetShippingRateTables' => [
            'method' => 'POST',
            'resource' => 'rate_table',
            'responseClass' => '\LT\eBaySDK\Account\Types\GetShippingRateTablesRestResponse',
            'params' => [
                'country_code' => [
                    'valid' => ['string']
                ]
            ]
        ],
        'CreateAReturnPolicy' => [
            'method' => 'POST',
            'resource' => 'return_policy',
            'responseClass' => '\LT\eBaySDK\Account\Types\CreateAReturnPolicyRestResponse',
            'params' => [
            ]
        ],
        'DeleteAReturnPolicy' => [
            'method' => 'DELETE',
            'resource' => 'return_policy/{return_policy_id}',
            'responseClass' => '\LT\eBaySDK\Account\Types\DeleteAReturnPolicyRestResponse',
            'params' => [
                'return_policy_id' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetReturnPoliciesByMarketplace' => [
            'method' => 'GET',
            'resource' => 'return_policy',
            'responseClass' => '\LT\eBaySDK\Account\Types\GetReturnPoliciesByMarketplaceRestResponse',
            'params' => [
                'marketplace_id' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetAReturnPolicyByID' => [
            'method' => 'GET',
            'resource' => 'return_policy/{returnPolicyId}',
            'responseClass' => '\LT\eBaySDK\Account\Types\GetAReturnPolicyByIDRestResponse',
            'params' => [
                'returnPolicyId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetAReturnPolicyByName' => [
            'method' => 'GET',
            'resource' => 'return_policy/get_by_policy_name',
            'responseClass' => '\LT\eBaySDK\Account\Types\GetAReturnPolicyByNameRestResponse',
            'params' => [
                'marketplace_id' => [
                    'valid' => ['string'],
                    'required' => true
                ],
                'name' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'UpdateAReturnPolicy' => [
            'method' => 'PUT',
            'resource' => 'return_policy/{return_policy_id}',
            'responseClass' => '\LT\eBaySDK\Account\Types\UpdateAReturnPolicyRestResponse',
            'params' => [
                'return_policy_id' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'CreateASalesTaxTable' => [
            'method' => 'PUT',
            'resource' => 'sales_tax/{countryCode}/{jurisdictionId}',
            'responseClass' => '\LT\eBaySDK\Account\Types\CreateASalesTaxTableRestResponse',
            'params' => [
                'countryCode' => [
                    'valid' => ['string'],
                    'required' => true
                ],
                'jurisdictionId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'DeleteASalesTaxTable' => [
            'method' => 'DELETE',
            'resource' => 'sales_tax/{countryCode}/{jurisdictionId}',
            'responseClass' => '\LT\eBaySDK\Account\Types\DeleteASalesTaxTableRestResponse',
            'params' => [
                'countryCode' => [
                    'valid' => ['string'],
                    'required' => true
                ],
                'jurisdictionId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetASalesTaxTable' => [
            'method' => 'GET',
            'resource' => 'sales_tax/{countryCode}/{jurisdictionId}',
            'responseClass' => '\LT\eBaySDK\Account\Types\GetASalesTaxTableRestResponse',
            'params' => [
                'countryCode' => [
                    'valid' => ['string'],
                    'required' => true
                ],
                'jurisdictionId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetAllSalesTaxTables' => [
            'method' => 'GET',
            'resource' => 'sales_tax',
            'responseClass' => '\LT\eBaySDK\Account\Types\GetAllSalesTaxTablesRestResponse',
            'params' => [
                'country_code' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ]
    ];

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\CreateAFulfillmentPolicyRestRequest $request
     * @return \LT\eBaySDK\Account\Types\CreateAFulfillmentPolicyRestResponse
     */
    public function createAFulfillmentPolicy(\LT\eBaySDK\Account\Types\CreateAFulfillmentPolicyRestRequest $request)
    {
        return $this->createAFulfillmentPolicyAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\CreateAFulfillmentPolicyRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAFulfillmentPolicyAsync(\LT\eBaySDK\Account\Types\CreateAFulfillmentPolicyRestRequest $request)
    {
        return $this->callOperationAsync('CreateAFulfillmentPolicy', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\DeleteAFulfillmentPolicyRestRequest $request
     * @return \LT\eBaySDK\Account\Types\DeleteAFulfillmentPolicyRestResponse
     */
    public function deleteAFulfillmentPolicy(\LT\eBaySDK\Account\Types\DeleteAFulfillmentPolicyRestRequest $request)
    {
        return $this->deleteAFulfillmentPolicyAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\DeleteAFulfillmentPolicyRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAFulfillmentPolicyAsync(\LT\eBaySDK\Account\Types\DeleteAFulfillmentPolicyRestRequest $request)
    {
        return $this->callOperationAsync('DeleteAFulfillmentPolicy', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetFulfillmentPoliciesByMarketplaceRestRequest $request
     * @return \LT\eBaySDK\Account\Types\GetFulfillmentPoliciesByMarketplaceRestResponse
     */
    public function getFulfillmentPoliciesByMarketplace(\LT\eBaySDK\Account\Types\GetFulfillmentPoliciesByMarketplaceRestRequest $request)
    {
        return $this->getFulfillmentPoliciesByMarketplaceAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetFulfillmentPoliciesByMarketplaceRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFulfillmentPoliciesByMarketplaceAsync(\LT\eBaySDK\Account\Types\GetFulfillmentPoliciesByMarketplaceRestRequest $request)
    {
        return $this->callOperationAsync('GetFulfillmentPoliciesByMarketplace', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetAFulfillmentPolicyByIDRestRequest $request
     * @return \LT\eBaySDK\Account\Types\GetAFulfillmentPolicyByIDRestResponse
     */
    public function getAFulfillmentPolicyByID(\LT\eBaySDK\Account\Types\GetAFulfillmentPolicyByIDRestRequest $request)
    {
        return $this->getAFulfillmentPolicyByIDAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetAFulfillmentPolicyByIDRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAFulfillmentPolicyByIDAsync(\LT\eBaySDK\Account\Types\GetAFulfillmentPolicyByIDRestRequest $request)
    {
        return $this->callOperationAsync('GetAFulfillmentPolicyByID', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetAFulfillmentPolicyByNameRestRequest $request
     * @return \LT\eBaySDK\Account\Types\GetAFulfillmentPolicyByNameRestResponse
     */
    public function getAFulfillmentPolicyByName(\LT\eBaySDK\Account\Types\GetAFulfillmentPolicyByNameRestRequest $request)
    {
        return $this->getAFulfillmentPolicyByNameAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetAFulfillmentPolicyByNameRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAFulfillmentPolicyByNameAsync(\LT\eBaySDK\Account\Types\GetAFulfillmentPolicyByNameRestRequest $request)
    {
        return $this->callOperationAsync('GetAFulfillmentPolicyByName', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\UpdateAFulfillmentPolicyRestRequest $request
     * @return \LT\eBaySDK\Account\Types\UpdateAFulfillmentPolicyRestResponse
     */
    public function updateAFulfillmentPolicy(\LT\eBaySDK\Account\Types\UpdateAFulfillmentPolicyRestRequest $request)
    {
        return $this->updateAFulfillmentPolicyAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\UpdateAFulfillmentPolicyRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAFulfillmentPolicyAsync(\LT\eBaySDK\Account\Types\UpdateAFulfillmentPolicyRestRequest $request)
    {
        return $this->callOperationAsync('UpdateAFulfillmentPolicy', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\CreateAPaymentPolicyRestRequest $request
     * @return \LT\eBaySDK\Account\Types\CreateAPaymentPolicyRestResponse
     */
    public function createAPaymentPolicy(\LT\eBaySDK\Account\Types\CreateAPaymentPolicyRestRequest $request)
    {
        return $this->createAPaymentPolicyAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\CreateAPaymentPolicyRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAPaymentPolicyAsync(\LT\eBaySDK\Account\Types\CreateAPaymentPolicyRestRequest $request)
    {
        return $this->callOperationAsync('CreateAPaymentPolicy', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\DeleteAPaymentPolicyRestRequest $request
     * @return \LT\eBaySDK\Account\Types\DeleteAPaymentPolicyRestResponse
     */
    public function deleteAPaymentPolicy(\LT\eBaySDK\Account\Types\DeleteAPaymentPolicyRestRequest $request)
    {
        return $this->deleteAPaymentPolicyAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\DeleteAPaymentPolicyRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAPaymentPolicyAsync(\LT\eBaySDK\Account\Types\DeleteAPaymentPolicyRestRequest $request)
    {
        return $this->callOperationAsync('DeleteAPaymentPolicy', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetPaymentPoliciesByMarketplaceRestRequest $request
     * @return \LT\eBaySDK\Account\Types\GetPaymentPoliciesByMarketplaceRestResponse
     */
    public function getPaymentPoliciesByMarketplace(\LT\eBaySDK\Account\Types\GetPaymentPoliciesByMarketplaceRestRequest $request)
    {
        return $this->getPaymentPoliciesByMarketplaceAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetPaymentPoliciesByMarketplaceRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentPoliciesByMarketplaceAsync(\LT\eBaySDK\Account\Types\GetPaymentPoliciesByMarketplaceRestRequest $request)
    {
        return $this->callOperationAsync('GetPaymentPoliciesByMarketplace', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetAPaymentPolicyByIDRestRequest $request
     * @return \LT\eBaySDK\Account\Types\GetAPaymentPolicyByIDRestResponse
     */
    public function getAPaymentPolicyByID(\LT\eBaySDK\Account\Types\GetAPaymentPolicyByIDRestRequest $request)
    {
        return $this->getAPaymentPolicyByIDAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetAPaymentPolicyByIDRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAPaymentPolicyByIDAsync(\LT\eBaySDK\Account\Types\GetAPaymentPolicyByIDRestRequest $request)
    {
        return $this->callOperationAsync('GetAPaymentPolicyByID', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetAPaymentPolicyByNameRestRequest $request
     * @return \LT\eBaySDK\Account\Types\GetAPaymentPolicyByNameRestResponse
     */
    public function getAPaymentPolicyByName(\LT\eBaySDK\Account\Types\GetAPaymentPolicyByNameRestRequest $request)
    {
        return $this->getAPaymentPolicyByNameAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetAPaymentPolicyByNameRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAPaymentPolicyByNameAsync(\LT\eBaySDK\Account\Types\GetAPaymentPolicyByNameRestRequest $request)
    {
        return $this->callOperationAsync('GetAPaymentPolicyByName', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\UpdateAPaymentPolicyRestRequest $request
     * @return \LT\eBaySDK\Account\Types\UpdateAPaymentPolicyRestResponse
     */
    public function updateAPaymentPolicy(\LT\eBaySDK\Account\Types\UpdateAPaymentPolicyRestRequest $request)
    {
        return $this->updateAPaymentPolicyAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\UpdateAPaymentPolicyRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAPaymentPolicyAsync(\LT\eBaySDK\Account\Types\UpdateAPaymentPolicyRestRequest $request)
    {
        return $this->callOperationAsync('UpdateAPaymentPolicy', $request);
    }

    /**
     * @return \LT\eBaySDK\Account\Types\GetAccountPrivilegesRestResponse
     */
    public function getAccountPrivileges()
    {
        return $this->getAccountPrivilegesAsync()->wait();
    }

    /**
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAccountPrivilegesAsync()
    {
        return $this->callOperationAsync('GetAccountPrivileges');
    }

    /**
     * @return \LT\eBaySDK\Account\Types\GetOptedInProgramsRestResponse
     */
    public function getOptedInPrograms()
    {
        return $this->getOptedInProgramsAsync()->wait();
    }

    /**
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOptedInProgramsAsync()
    {
        return $this->callOperationAsync('GetOptedInPrograms');
    }

    /**
     * @param \LT\eBaySDK\Account\Types\OptInToProgramRestRequest $request
     * @return \LT\eBaySDK\Account\Types\OptInToProgramRestResponse
     */
    public function optInToProgram(\LT\eBaySDK\Account\Types\OptInToProgramRestRequest $request)
    {
        return $this->optInToProgramAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\OptInToProgramRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function optInToProgramAsync(\LT\eBaySDK\Account\Types\OptInToProgramRestRequest $request)
    {
        return $this->callOperationAsync('OptInToProgram', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\OptOutOfProgramRestRequest $request
     * @return \LT\eBaySDK\Account\Types\OptOutOfProgramRestResponse
     */
    public function optOutOfProgram(\LT\eBaySDK\Account\Types\OptOutOfProgramRestRequest $request)
    {
        return $this->optOutOfProgramAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\OptOutOfProgramRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function optOutOfProgramAsync(\LT\eBaySDK\Account\Types\OptOutOfProgramRestRequest $request)
    {
        return $this->callOperationAsync('OptOutOfProgram', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetShippingRateTablesRestRequest $request
     * @return \LT\eBaySDK\Account\Types\GetShippingRateTablesRestResponse
     */
    public function getShippingRateTables(\LT\eBaySDK\Account\Types\GetShippingRateTablesRestRequest $request)
    {
        return $this->getShippingRateTablesAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetShippingRateTablesRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getShippingRateTablesAsync(\LT\eBaySDK\Account\Types\GetShippingRateTablesRestRequest $request)
    {
        return $this->callOperationAsync('GetShippingRateTables', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\CreateAReturnPolicyRestRequest $request
     * @return \LT\eBaySDK\Account\Types\CreateAReturnPolicyRestResponse
     */
    public function createAReturnPolicy(\LT\eBaySDK\Account\Types\CreateAReturnPolicyRestRequest $request)
    {
        return $this->createAReturnPolicyAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\CreateAReturnPolicyRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAReturnPolicyAsync(\LT\eBaySDK\Account\Types\CreateAReturnPolicyRestRequest $request)
    {
        return $this->callOperationAsync('CreateAReturnPolicy', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\DeleteAReturnPolicyRestRequest $request
     * @return \LT\eBaySDK\Account\Types\DeleteAReturnPolicyRestResponse
     */
    public function deleteAReturnPolicy(\LT\eBaySDK\Account\Types\DeleteAReturnPolicyRestRequest $request)
    {
        return $this->deleteAReturnPolicyAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\DeleteAReturnPolicyRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAReturnPolicyAsync(\LT\eBaySDK\Account\Types\DeleteAReturnPolicyRestRequest $request)
    {
        return $this->callOperationAsync('DeleteAReturnPolicy', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetReturnPoliciesByMarketplaceRestRequest $request
     * @return \LT\eBaySDK\Account\Types\GetReturnPoliciesByMarketplaceRestResponse
     */
    public function getReturnPoliciesByMarketplace(\LT\eBaySDK\Account\Types\GetReturnPoliciesByMarketplaceRestRequest $request)
    {
        return $this->getReturnPoliciesByMarketplaceAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetReturnPoliciesByMarketplaceRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnPoliciesByMarketplaceAsync(\LT\eBaySDK\Account\Types\GetReturnPoliciesByMarketplaceRestRequest $request)
    {
        return $this->callOperationAsync('GetReturnPoliciesByMarketplace', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetAReturnPolicyByIDRestRequest $request
     * @return \LT\eBaySDK\Account\Types\GetAReturnPolicyByIDRestResponse
     */
    public function getAReturnPolicyByID(\LT\eBaySDK\Account\Types\GetAReturnPolicyByIDRestRequest $request)
    {
        return $this->getAReturnPolicyByIDAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetAReturnPolicyByIDRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAReturnPolicyByIDAsync(\LT\eBaySDK\Account\Types\GetAReturnPolicyByIDRestRequest $request)
    {
        return $this->callOperationAsync('GetAReturnPolicyByID', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetAReturnPolicyByNameRestRequest $request
     * @return \LT\eBaySDK\Account\Types\GetAReturnPolicyByNameRestResponse
     */
    public function getAReturnPolicyByName(\LT\eBaySDK\Account\Types\GetAReturnPolicyByNameRestRequest $request)
    {
        return $this->getAReturnPolicyByNameAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetAReturnPolicyByNameRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAReturnPolicyByNameAsync(\LT\eBaySDK\Account\Types\GetAReturnPolicyByNameRestRequest $request)
    {
        return $this->callOperationAsync('GetAReturnPolicyByName', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\UpdateAReturnPolicyRestRequest $request
     * @return \LT\eBaySDK\Account\Types\UpdateAReturnPolicyRestResponse
     */
    public function updateAReturnPolicy(\LT\eBaySDK\Account\Types\UpdateAReturnPolicyRestRequest $request)
    {
        return $this->updateAReturnPolicyAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\UpdateAReturnPolicyRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAReturnPolicyAsync(\LT\eBaySDK\Account\Types\UpdateAReturnPolicyRestRequest $request)
    {
        return $this->callOperationAsync('UpdateAReturnPolicy', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\CreateASalesTaxTableRestRequest $request
     * @return \LT\eBaySDK\Account\Types\CreateASalesTaxTableRestResponse
     */
    public function createASalesTaxTable(\LT\eBaySDK\Account\Types\CreateASalesTaxTableRestRequest $request)
    {
        return $this->createASalesTaxTableAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\CreateASalesTaxTableRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createASalesTaxTableAsync(\LT\eBaySDK\Account\Types\CreateASalesTaxTableRestRequest $request)
    {
        return $this->callOperationAsync('CreateASalesTaxTable', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\DeleteASalesTaxTableRestRequest $request
     * @return \LT\eBaySDK\Account\Types\DeleteASalesTaxTableRestResponse
     */
    public function deleteASalesTaxTable(\LT\eBaySDK\Account\Types\DeleteASalesTaxTableRestRequest $request)
    {
        return $this->deleteASalesTaxTableAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\DeleteASalesTaxTableRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteASalesTaxTableAsync(\LT\eBaySDK\Account\Types\DeleteASalesTaxTableRestRequest $request)
    {
        return $this->callOperationAsync('DeleteASalesTaxTable', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetASalesTaxTableRestRequest $request
     * @return \LT\eBaySDK\Account\Types\GetASalesTaxTableRestResponse
     */
    public function getASalesTaxTable(\LT\eBaySDK\Account\Types\GetASalesTaxTableRestRequest $request)
    {
        return $this->getASalesTaxTableAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetASalesTaxTableRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getASalesTaxTableAsync(\LT\eBaySDK\Account\Types\GetASalesTaxTableRestRequest $request)
    {
        return $this->callOperationAsync('GetASalesTaxTable', $request);
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetAllSalesTaxTablesRestRequest $request
     * @return \LT\eBaySDK\Account\Types\GetAllSalesTaxTablesRestResponse
     */
    public function getAllSalesTaxTables(\LT\eBaySDK\Account\Types\GetAllSalesTaxTablesRestRequest $request)
    {
        return $this->getAllSalesTaxTablesAsync($request)->wait();
    }

    /**
     * @param \LT\eBaySDK\Account\Types\GetAllSalesTaxTablesRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllSalesTaxTablesAsync(\LT\eBaySDK\Account\Types\GetAllSalesTaxTablesRestRequest $request)
    {
        return $this->callOperationAsync('GetAllSalesTaxTables', $request);
    }
}
