<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace LT\eBaySDK\Test\Merchandising\Types;

use LT\eBaySDK\Merchandising\Types\MerchandisingServiceProductResponse;

class MerchandisingServiceProductResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new MerchandisingServiceProductResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\LT\eBaySDK\Merchandising\Types\MerchandisingServiceProductResponse', $this->obj);
    }

    public function testExtendsBaseMerchandisingServiceResponse()
    {
        $this->assertInstanceOf('\LT\eBaySDK\Merchandising\Types\BaseMerchandisingServiceResponse', $this->obj);
    }
}
