<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace LT\eBaySDK\Test\PostOrder\Types;

use LT\eBaySDK\PostOrder\Types\AddShippingLabelInfoRestRequest;

class AddShippingLabelInfoRestRequestTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new AddShippingLabelInfoRestRequest();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\LT\eBaySDK\PostOrder\Types\AddShippingLabelInfoRestRequest', $this->obj);
    }

    public function testExtendsProvideLabelRequest()
    {
        $this->assertInstanceOf('\LT\eBaySDK\PostOrder\Types\ProvideLabelRequest', $this->obj);
    }
}
