<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace LT\eBaySDK\Test\PostOrder\Types;

use LT\eBaySDK\PostOrder\Types\CreateReturnRequestRestRequest;

class CreateReturnRequestRestRequestTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new CreateReturnRequestRestRequest();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\LT\eBaySDK\PostOrder\Types\CreateReturnRequestRestRequest', $this->obj);
    }

    public function testExtendsCreateReturnRequest()
    {
        $this->assertInstanceOf('\LT\eBaySDK\PostOrder\Types\CreateReturnRequest', $this->obj);
    }
}
