<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace LT\eBaySDK\Test\PostOrder\Types;

use LT\eBaySDK\PostOrder\Types\CreateReturnDraftRestResponse;

class CreateReturnDraftRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new CreateReturnDraftRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\LT\eBaySDK\PostOrder\Types\CreateReturnDraftRestResponse', $this->obj);
    }

    public function testExtendsSetReturnCreationSessionResponse()
    {
        $this->assertInstanceOf('\LT\eBaySDK\PostOrder\Types\SetReturnCreationSessionResponse', $this->obj);
    }
}
